const customers = [
  {
    customer_number: 1,
    name: "Break Time",
    permit_number: "102633106",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
  {
    customer_number: 2,
    name: "Romeritos Cat.",
    permit_number: "239867904",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
  {
    customer_number: 3,
    name: "Lucivanna",
    permit_number: "249942368",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
  {
    customer_number: 4,
    name: "Chiquita - Nor",
    permit_number: "102858376",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
  {
    customer_number: 5,
    name: "Chiquita - Imel",
    permit_number: "102858376",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
  {
    customer_number: 6,
    name: "Pho Xpress",
    permit_number: "100962107",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
  {
    customer_number: 7,
    name: "Break Time",
    permit_number: "232153024",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
  {
    customer_number: 8,
    name: "Gilbert Flores",
    permit_number: "100786400",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
  {
    customer_number: 9,
    name: "Lazaro Alvarez",
    permit_number: "99784198",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
  {
    customer_number: 10,
    name: "Totis FS - Lu",
    permit_number: "262721664",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
  {
    customer_number: 11,
    name: "Lupita Totis",
    permit_number: "100267034",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
  {
    customer_number: 12,
    name: "Jerry Dean W",
    permit_number: "102216458",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
  {
    customer_number: 13,
    name: "Cocinita La Mi",
    permit_number: "200945728",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
  {
    customer_number: 14,
    name: "Pho Saigon E",
    permit_number: "100653687",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
  {
    customer_number: 15,
    name: "Carry Out",
    permit_number: "0",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
  {
    customer_number: 16,
    name: "Haad Sai Tha",
    permit_number: "12421233",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
  {
    customer_number: 17,
    name: "Pho Xpress D",
    permit_number: "100962107",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
  {
    customer_number: 18,
    name: "BRANDON A",
    permit_number: "245439200",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
  {
    customer_number: 19,
    name: "EMMA CARO",
    permit_number: "223903072",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
  {
    customer_number: 20,
    name: "Chiquita - Imel",
    permit_number: "102858376",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
  {
    customer_number: 21,
    name: "Garcia Baltaz",
    permit_number: "0",
    truck_number: "",
    phone: "",
    email: "",
    address: "",
    notes: "",
  },
];

module.exports = customers;